version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8819
      - POSTGRES_DB=ignite
    volumes: 
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: ignite
    ports:
      - 8819:8819
    volumes:
      - .:/usr/app
    network_mode: host


volumes:
  pgdata:
    driver: local
  
